name: Update Jira on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  update-jira:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Extract issue key
        id: extract
        run: |
          ISSUE_KEY=$(echo "${{ github.event.pull_request.title }}" | grep -oE '[A-Z]+-[0-9]+')
          echo "ISSUE_KEY=$ISSUE_KEY" >> $GITHUB_ENV

      - name: Authenticate with Jira
        uses: atlassian/gajira-login@v3
        with:
          site: ${{ secrets.JIRA_BASE_URL }}
          email: ${{ secrets.JIRA_USER_EMAIL }}
          apiToken: ${{ secrets.JIRA_API_TOKEN }}

      - name: Transition Jira issue to Done
        uses: atlassian/gajira-transition@v3
        with:
          issue: ${{ env.ISSUE_KEY }}
          transition: "Done"
