name: Update Jira on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  update-jira:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Extract issue key
        id: extract
        run: |
          ISSUE_KEY=$(echo "${{ github.event.pull_request.title }}" | grep -oE '[A-Z]+-[0-9]+')
          echo "ISSUE_KEY=$ISSUE_KEY" >> $GITHUB_ENV

      - name: Update Jira issue status
        uses: atlassian/gajira-transition@v3
        with:
          from: "In Progress"
          to: "Done"
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_ISSUE: ${{ env.ISSUE_KEY }}
